// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrl-whwBYSiu6MEOfRePY3BfUwXLbQ3_0',
    appId: '1:728287730824:web:e746091037e1245753533d',
    messagingSenderId: '728287730824',
    projectId: 'campus-market-a53aa',
    authDomain: 'campus-market-a53aa.firebaseapp.com',
    storageBucket: 'campus-market-a53aa.firebasestorage.app',
    measurementId: 'G-5VLM3RRMBK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOaK1rpQDG0sKBy5W2uzD5qExCGGP-GRQ',
    appId: '1:728287730824:android:b73c2ea84d8a0fc653533d',
    messagingSenderId: '728287730824',
    projectId: 'campus-market-a53aa',
    storageBucket: 'campus-market-a53aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlWROXvm_x5cnSC0JsEIbsQwCZvv4FMmg',
    appId: '1:728287730824:ios:3461c41acdf41e7b53533d',
    messagingSenderId: '728287730824',
    projectId: 'campus-market-a53aa',
    storageBucket: 'campus-market-a53aa.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlWROXvm_x5cnSC0JsEIbsQwCZvv4FMmg',
    appId: '1:728287730824:ios:3461c41acdf41e7b53533d',
    messagingSenderId: '728287730824',
    projectId: 'campus-market-a53aa',
    storageBucket: 'campus-market-a53aa.firebasestorage.app',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrl-whwBYSiu6MEOfRePY3BfUwXLbQ3_0',
    appId: '1:728287730824:web:4db900b6fb15f9e853533d',
    messagingSenderId: '728287730824',
    projectId: 'campus-market-a53aa',
    authDomain: 'campus-market-a53aa.firebaseapp.com',
    storageBucket: 'campus-market-a53aa.firebasestorage.app',
    measurementId: 'G-QVHGYSHVHG',
  );
}
